In [1]:
import pandas as pd
from jupyter_dash import JupyterDash
from dash import dcc, html, dash_table, Input, Output
import plotly.express as px
import pandas as pd
# Load both sheets
file_path = "Data1.xlsx"
df_employee = pd.read_excel(file_path, sheet_name="df_employee")

df_employee.head()

,Unnamed: 0,EmployeeID,Full Name,Gender,Age,BusinessTravel,Department,DistanceFromHome,State,Ethnicity,...,MaritalStatus,Salary,StockOptionLevel,OverTime,HireDate,Attrition,YearsAtCompany,YearsInMostRecentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,79F7-78EC,Alessandra Storrock,Non-Binary,27,Some Travel,Sales,37,California,White,...,Single,141998,0,Yes,2013-12-14,Yes,5,5,5,1
1,1,B61E-0F26,Care Heintze,Male,28,Frequent Traveller,Technology,3,New York,White,...,Married,58993,1,Yes,2014-11-07,Yes,7,2,7,1
2,2,00A3-2445,Wyatt Ziehm,Male,30,Some Travel,Technology,6,California,Black or African American,...,Married,126238,0,No,2012-03-08,No,10,3,6,6
3,3,F5E3-48BB,Zenia Rattery,Female,25,Frequent Traveller,Human Resources,3,California,American Indian or Alaska Native,...,Married,23547,0,No,2015-01-13,Yes,3,0,2,1
4,4,00B0-F199,Trueman Jirasek,Male,23,Some Travel,Sales,35,California,White,...,Married,97824,1,Yes,2020-03-16,Yes,1,0,1,0

In [2]:

import pandas as pd
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

# Example data loading (replace with your actual df)
df = df_employee

app = Dash(__name__)

color_palette = ['#27445D', '#497D74']

app.layout = html.Div([
    html.Div([
        html.H1("Employee Attrition Dashboard", style={
            "backgroundColor": "#27445D",
            "color": "white",
            "padding": "6px 10px",
            "fontSize": "24px",
            "textAlign": "center",
            "fontWeight": "bold",
            "margin": "0"
        })
    ]),
    html.Div([
        html.Label("Select Department:", style={
            "color": "#27445D", "fontWeight": "bold"
        }),
        dcc.Dropdown(
            id="department-dropdown",
            options=[{"label": "All Departments", "value": "All"}] +
                    [{"label": dept, "value": dept} for dept in sorted(df["Department"].unique())],
            value="All"
        )
    ], style={"width": "300px", "margin": "10px 0"}),

    dcc.Tabs([
        dcc.Tab(label="ðŸ“Š Attrition Overview", children=[
            html.Div([
                dcc.Graph(id="attrition-bar", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-pie", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-overtime", style={"width": "32%", "display": "inline-block", "height": "300px"}),

                dcc.Graph(id="attrition-business-travel", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-department", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-education-field", style={"width": "32%", "display": "inline-block", "height": "300px"})
            ])
        ]),

        dcc.Tab(label="ðŸ“ˆ Employee Stats", children=[
            html.Div([
                dcc.Graph(id="attrition-gender", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-jobrole", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="attrition-stock-options", style={"width": "32%", "display": "inline-block", "height": "300px"}),

                dcc.Graph(id="age-dist", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="distance-dist", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="salary-dist", style={"width": "32%", "display": "inline-block", "height": "300px"})
            ])
        ]),

        dcc.Tab(label="ðŸ§­ Career Timeline", children=[
            html.Div([
                dcc.Graph(id="years-manager-dist", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="years-company-dist", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="years-role-dist", style={"width": "32%", "display": "inline-block", "height": "300px"}),

                dcc.Graph(id="promotion-pie-stagnant", style={"width": "49%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="promotion-pie-recent", style={"width": "49%", "display": "inline-block", "height": "300px"})
            ])
        ]),

        dcc.Tab(label="ðŸ‘¥ Personal Insights", children=[
            html.Div([
                dcc.Graph(id="marital-status", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="ethnicity", style={"width": "32%", "display": "inline-block", "height": "300px"}),
                dcc.Graph(id="age-vs-salary", style={"width": "32%", "display": "inline-block", "height": "300px"})
            ])
        ])
    ],
        colors={
            "border": "#d6d6d6",
            "primary": "#27445D",
            "background": "#f5f8fa"
        },
        style={
            "fontWeight": "bold",
            "color": "#27445D",
            "fontSize": "16px"
        },
        parent_style={"marginBottom": "10px"}
    )
], style={
    "transform": "scale(0.87)",
    "transformOrigin": "top center",
    "maxWidth": "1920px",
    "margin": "0 auto",
    "backgroundColor": "#f5f8fa",
    "paddingBottom": "20px"
})

@app.callback(
    [
        Output("attrition-bar", "figure"),
        Output("attrition-pie", "figure"),
        Output("attrition-overtime", "figure"),
        Output("attrition-business-travel", "figure"),
        Output("attrition-department", "figure"),
        Output("attrition-education-field", "figure"),
        Output("attrition-gender", "figure"),
        Output("attrition-jobrole", "figure"),
        Output("attrition-stock-options", "figure"),
        Output("age-dist", "figure"),
        Output("distance-dist", "figure"),
        Output("salary-dist", "figure"),
        Output("years-manager-dist", "figure"),
        Output("years-company-dist", "figure"),
        Output("years-role-dist", "figure"),
        Output("promotion-pie-stagnant", "figure"),
        Output("promotion-pie-recent", "figure"),
        Output("marital-status", "figure"),
        Output("ethnicity", "figure"),
        Output("age-vs-salary", "figure")
    ],
    [Input("department-dropdown", "value")]
)
def update_all(department):
    dff = df.copy()
    if department != "All":
        dff = dff[dff["Department"] == department]

    def countplot(x, hue=None, title=""):
        fig = px.histogram(dff, x=x, color=hue, barmode="group",
                           color_discrete_sequence=color_palette)
        fig.update_layout(xaxis_title="", title=title, plot_bgcolor="white", paper_bgcolor="white")
        return fig

    def histplot(x, hue=None, title=""):
        return px.histogram(dff, x=x, color=hue, nbins=30,
                            color_discrete_sequence=color_palette, title=title)

    attr_bar = countplot("Attrition", title="Attrition Count")
    attr_pie = px.pie(dff, names="Attrition", color_discrete_sequence=color_palette)
    attr_pie.update_layout(title="Attrition Rate", plot_bgcolor="white", paper_bgcolor="white")

    overtime = countplot("OverTime", "Attrition", title="Impact of Overtime on Attrition")
    travel = countplot("BusinessTravel", "Attrition", title="Impact of Business Travel on Attrition")
    dept = countplot("Department", "Attrition", title="Impact of Department on Attrition")
    edu = countplot("EducationField", "Attrition", title="Impact of Education Field on Attrition")
    gender = countplot("Gender", "Attrition", title="Impact of Gender on Attrition")
    job = countplot("JobRole", "Attrition", title="Impact of Job Role on Attrition")
    stock = countplot("StockOptionLevel", "Attrition", title="Impact of Stock Option Level on Attrition")

    age = histplot("Age", "Attrition", title="Impact of Age on Attrition")
    dist = histplot("DistanceFromHome", "Attrition", title="Impact of Distance From Home on Attrition")
    salary = histplot("Salary", "Attrition", title="Impact of Salary on Attrition")
    curr_mgr = histplot("YearsWithCurrManager", "Attrition", title="Impact of Years with Current Manager on Attrition")
    years_comp = histplot("YearsAtCompany", "Attrition", title="Impact of Years at Company on Attrition")
    years_role = histplot("YearsInMostRecentRole", "Attrition", title="Impact of Years in Most Recent Role on Attrition")

    stagnant_df = dff[dff['YearsSinceLastPromotion'] >= 5]
    recent_df = dff[dff['YearsSinceLastPromotion'] <= 5]

    stagnation_counts = stagnant_df['Attrition'].value_counts(normalize=True) * 100
    recent_counts = recent_df['Attrition'].value_counts(normalize=True) * 100

    promo_pie_stagnant = px.pie(
        names=stagnation_counts.index,
        values=stagnation_counts.values,
        title="Attrition Rate for Employees Promoted in 5+ Years",
        color_discrete_sequence=color_palette
    )

    promo_pie_recent = px.pie(
        names=recent_counts.index,
        values=recent_counts.values,
        title="Attrition Rate for Employees not Promoted Within 5 Years",
        color_discrete_sequence=color_palette
    )

    marital = countplot("MaritalStatus", "Attrition", title="Impact of Marital Status on Attrition")
    ethnicity = countplot("Ethnicity", "Attrition", title="Impact of Ethnicity on Attrition")
    reg = px.scatter(dff, x="Age", y="Salary", trendline="ols", opacity=0.4,
                     title="Age vs Salary Correlation", color_discrete_sequence=["#27445D"])
    reg.update_layout(xaxis_title="", plot_bgcolor="white", paper_bgcolor="white")

    return attr_bar, attr_pie, overtime, travel, dept, edu, gender, job, stock, \
           age, dist, salary, curr_mgr, years_comp, years_role, \
           promo_pie_stagnant, promo_pie_recent, marital, ethnicity, reg

if __name__ == '__main__':
    app.run(debug=True)